import { readFile } from "fs/promises";
import path from "path";
import glob from "tiny-glob";
import { factory, Node } from "typescript";
import {
  Driver,
  Session,
  snakeToCamelCaseConversion,
  TypedValues,
  Types,
  withRetries,
} from "ydb-sdk";
import emit from "./emit";
import getImports from "./getImports";
// import getQueryOptions from "./getQueryOptions";
import processFile from "./processFile";

const IMPORTS = [
  TypedValues.name,
  Types.name,
  Driver.name,
  Session.name,
  withRetries.name,
];

export const processFiles = async (files: File[], driver: Driver) => {
  const comment = factory.createJSDocComment(
    "This file is generated by ydb-ts-codegen and should not be modified directly"
  );
  let result: File[] = [];
  for (const file of files) {
    let nodes: Node[] = [comment, getImports(IMPORTS, "ydb-sdk")];
    const processedFile = await processFile(
      snakeToCamelCaseConversion.ydbToJs(file.name),
      file.content,
      driver
    );
    nodes = nodes.concat(processedFile);
    result.push({
      name: snakeToCamelCaseConversion.ydbToJs(file.name),
      content: emit(nodes),
    });
  }
  return result;
};

type File = {
  name: string;
  content: string;
};

export const processFolder = async (source: string, driver: Driver) => {
  const target = `${source}/**/*.sql`;
  const filenames = await glob(target, {
    absolute: true,
    filesOnly: true,
  });
  const files = await Promise.all(
    filenames.map(async (filename) => ({
      name: path.parse(filename).name,
      content: await readFile(filename, "utf-8"),
    }))
  );
  return processFiles(files, driver);
};
